# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Pictory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pictory
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'JTAppleCalendar', '~> 7.0'

  target 'PictoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PictoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
